In [1]:
#Set working directory
import os
os.chdir('C://Users//Admin//Downloads')

In [2]:
# Import pandas library.
import pandas as pd
from pandas import DataFrame

In [4]:
#The file "nyc-rolling-sales_clean.csvPreview the document" contains New York City 
#property sales data taken from Kaggle (Links to an external site.). 
#The data has already been cleaned and a few columns have been dropped.
#Write your own code in Python that performs the following operations on this dataset:
file = pd.read_csv('nyc-rolling-sales_clean.csv')

In [13]:
#Create a new column "year of sale" by extracting year information from "SALE DATE" column
file['SALE DATE'] = pd.to_datetime(file['SALE DATE'])
file['year of sale'] = file['SALE DATE'].dt.year
file

,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,BUILDING CLASS AT PRESENT,ADDRESS,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,SALE PRICE,SALE DATE,year of sale
0,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,387,153,D9,629 EAST 5TH STREET,10009,24,0,24,4489,18523,1920,16232000,2016-11-07,2016
1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,376,14,C6,244 EAST 7TH STREET,10009,24,0,24,4131,16776,1928,11900000,2017-06-21,2017
2,ALPHABET CITY,22 STORE BUILDINGS,4,390,34,K4,115 AVENUE C,10009,0,1,1,1218,3586,1899,3700000,2016-09-28,2016
3,CHELSEA,01 ONE FAMILY DWELLINGS,1,771,52,A9,224 WEST 22ND STREET,10011,1,0,1,1975,3855,1901,7425000,2016-12-30,2016
4,CHELSEA,01 ONE FAMILY DWELLINGS,1,772,29,A4,231 WEST 22ND STREET,10011,1,0,1,1588,5653,1900,10,2017-01-30,2017
5,CHELSEA,01 ONE FAMILY DWELLINGS,1,772,29,A4,231 WEST 22ND STREET,10011,1,0,1,1588,5653,1900,10,2017-01-30,2017
6,CHELSEA,01 ONE FAMILY DWELLINGS,1,772,29,A4,231 WEST 22ND STREET,10011,1,0,1,1588,5653,1900,10,2017-01-30,2017
7,CHELSEA,02 TWO FAMILY DWELLINGS,1,769,49,S2,218 WEST 20TH STREET,10011,2,1,3,2150,4978,1920,7750000,2017-04-17,2017
8,CHELSEA,03 THREE FAMILY DWELLINGS,1,719,67,C0,444 WEST 22ND STREET,10011,3,0,3,2469,3725,1901,8300000,2017-02-02,2017
9,CHELSEA,07 RENTALS - WALKUP APARTMENTS,2,743,56,C5,318 WEST 20TH STREET,10011,24,0,24,2307,4500,1900,7375000,2017-02-06,2017
10,CHELSEA,07 RENTALS - WALKUP APARTMENTS,2,764,68,C4,256 WEST 15TH STREET,10011,22,2,24,2581,13056,1901,14100000,2017-03-23,2017
11,CHELSEA,07 RENTALS - WALKUP APARTMENTS,2,790,9,C7,147 WEST 14TH STREET,10011,15,1,16,2077,6335,1901,5500000,2017-02-02,2017
12,CHELSEA,08 RENTALS - ELEVATOR APARTMENTS,2,794,11,D7,155 WEST 18TH,10011,30,2,32,10053,78882,2014,2341975,2016-10-28,2016
13,CHELSEA,09 COOPS - WALKUP APARTMENTS,2,744,32,C6,309 WEST 20TH STREET,10011,24,0,24,4600,12200,1850,282000,2016-10-19,2016
14,CHELSEA,21 OFFICE BUILDINGS,4,692,63,O2,558 WEST 21ST STREET,10011,0,3,3,1360,4080,1900,17300000,2017-06-30,2017
15,CHELSEA,21 OFFICE BUILDINGS,4,790,32,O1,531-537 AVENUE OF THE AMER,10011,1,1,1,6468,14056,1953,42400000,2017-04-18,2017
16,CHELSEA,21 OFFICE BUILDINGS,4,801,24,O3,119 WEST 25TH STREET,10001,0,13,13,9875,113062,1906,150000000,2016-12-16,2016
17,CHELSEA,21 OFFICE BUILDINGS,4,801,58,O5,128 WEST 26TH STREET,10001,0,5,5,2469,10250,1930,10150000,2017-07-17,2017
18,CHELSEA,22 STORE BUILDINGS,4,696,28,K1,507 WEST 24TH,10011,0,1,1,3950,7900,2013,10750000,2016-12-28,2016
19,CHELSEA,22 STORE BUILDINGS,4,716,2,K4,132 TENTH AVENUE,10011,0,1,1,1675,3909,1910,8818181,2016-11-04,2016
20,CHELSEA,22 STORE BUILDINGS,4,717,5,K1,459 WEST 19TH STREET,10011,0,1,1,3800,3800,1910,20000000,2017-06-27,2017
21,CHELSEA,22 STORE BUILDINGS,4,773,1,K2,258 8 AVENUE,10011,0,4,4,19750,39500,1932,107250000,2017-08-08,2017
22,CHELSEA,22 STORE BUILDINGS,4,790,36,K4,539 AVENUE OF THE AMER,10011,2,2,4,1586,4271,1920,10600000,2017-04-18,2017
23,CHELSEA,23 LOFT BUILDINGS,4,795,19,L8,137 WEST 19TH STREET,10011,1,5,6,1878,11250,1910,10500000,2016-09-30,2016
24,CHELSEA,23 LOFT BUILDINGS,4,799,63,L8,140 WEST 24TH STREET,10011,0,3,3,1852,3980,1920,9174156,2017-01-18,2017
25,CHELSEA,23 LOFT BUILDINGS,4,801,19,L1,133 WEST 25TH STREET,10001,0,19,19,4937,45449,1921,33000000,2017-02-01,2017
26,CHELSEA,25 LUXURY HOTELS,4,801,71,H1,152 WEST 26TH STREET,10001,0,1,1,9826,122236,2010,139725000,2016-12-05,2016
27,CHELSEA,26 OTHER HOTELS,4,753,33,H8,305 WEST 29TH STREET,10001,0,1,1,2271,5260,1900,4300000,2017-07-12,2017
28,CHELSEA,26 OTHER HOTELS,4,772,64,H3,216-222 WEST 23RD STREET,10011,0,10,10,17281,170750,1900,92007576,2016-10-28,2016
29,CHELSEA,37 RELIGIOUS FACILITIES,4,799,25,M1,125 WEST 23RD STREET,10011,0,1,1,12343,21183,1920,50350000,2016-11-03,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42662,WOODROW,02 TWO FAMILY DWELLINGS,1,6967,25,B9,1019 RATHBUN AVENUE,10309,2,0,2,2500,1440,1987,595000,2017-05-12,2017
42663,WOODROW,02 TWO FAMILY DWELLINGS,1,6967,37,B9,1035 RATHBUN AVENUE,10309,2,0,2,2500,1440,1987,445000,2016-11-17,2016
42664,WOODROW,02 TWO FAMILY DWELLINGS,1,6970,26,B2,1053 SINCLAIR AVENUE,10309,2,0,2,8740,3160,1986,785000,2017-06-23,2017
42665,WOODROW,02 TWO FAMILY DWELLINGS,1,7013,30,B2,60 MARISA CIRCLE,10309,2,0,2,2685,2265,1984,570000,2017-05-31,2017
42666,WOODROW,02 TWO FAMILY DWELLINGS,1,7013,70,B2,136 MARISA CIRCLE,10309,2,0,2,3640,2576,1984,722000,2017-02-07,2017
42667,WOODROW,02 TWO FAMILY DWELLINGS,1,7013,158,B2,149 MARISA CIRCLE,10309,2,0,2,2943,1976,1984,545000,2016-12-29,2016
42668,WOODROW,02 TWO FAMILY DWELLINGS,1,7020,143,B2,1452 WOODROW ROAD,10309,2,0,2,11100,3560,1989,875000,2016-09-05,2016
42669,WOODROW,02 TWO FAMILY DWELLINGS,1,7020,160,B2,574 MAGUIRE AVENUE,10309,2,0,2,21528,2650,1985,875000,2017-05-22,2017
42670,WOODROW,02 TWO FAMILY DWELLINGS,1,7020,398,B2,72 DEXTER AVENUE,10309,2,0,2,5260,2600,2001,840000,2016-12-07,2016
42671,WOODROW,02 TWO FAMILY DWELLINGS,1,7020,408,B2,56 DEXTER AVENUE,10309,2,0,2,8306,2600,2001,772500,2017-03-30,2017
42672,WOODROW,02 TWO FAMILY DWELLINGS,1,7020,423,B2,35 LYNBROOK AVENUE,10309,2,0,2,5060,2600,2001,740000,2017-01-04,2017
42673,WOODROW,02 TWO FAMILY DWELLINGS,1,7092,15,B9,96 CRABTREE AVENUE,10309,2,0,2,2337,1964,2010,590000,2017-03-01,2017
42674,WOODROW,02 TWO FAMILY DWELLINGS,1,7092,113,B9,98 CRABTREE AVENUE,10309,2,0,2,2429,1798,2010,580000,2017-04-26,2017
42675,WOODROW,02 TWO FAMILY DWELLINGS,1,7092,140,B9,10 TRINA LANE,10309,2,0,2,3936,1470,2004,550000,2017-06-20,2017
42676,WOODROW,02 TWO FAMILY DWELLINGS,1,7105,2,B9,118 TURNER STREET,10309,2,0,2,6268,2206,2010,545000,2016-11-16,2016
42677,WOODROW,02 TWO FAMILY DWELLINGS,1,7105,660,B2,125 CLAY PIT ROAD,10309,2,0,2,10935,2683,1998,800000,2017-01-09,2017
42678,WOODROW,02 TWO FAMILY DWELLINGS,1,7267,130,B9,65 SHARROTTS LANE,10309,2,0,2,4300,2170,1998,642500,2017-06-22,2017
42679,WOODROW,02 TWO FAMILY DWELLINGS,1,7267,131,B9,67 SHARROTTS LANE,10309,2,0,2,4700,2170,1998,408092,2016-09-26,2016
42680,WOODROW,02 TWO FAMILY DWELLINGS,1,7267,182,B2,27 RED CEDAR LANE,10309,2,0,2,3985,2700,1996,600000,2017-02-27,2017
42681,WOODROW,02 TWO FAMILY DWELLINGS,1,7267,202,B9,30 HEMLOCK LANE,10309,2,0,2,3801,2704,1996,610000,2016-12-05,2016
42682,WOODROW,02 TWO FAMILY DWELLINGS,1,7267,218,B2,33 WHITE OAK LANE,10309,2,0,2,7885,2704,1996,645000,2017-08-04,2017
42683,WOODROW,02 TWO FAMILY DWELLINGS,1,7267,244,B2,19 SPRUCE LANE,10309,2,0,2,3800,2700,1996,168000,2017-01-19,2017
42684,WOODROW,02 TWO FAMILY DWELLINGS,1,7267,249,B2,48 WHITE OAK LANE,10309,2,0,2,4350,2840,1996,625000,2016-10-18,2016
42685,WOODROW,02 TWO FAMILY DWELLINGS,1,7316,93,B2,125 DARNELL LANE,10309,2,0,2,3325,1300,1995,509000,2016-10-31,2016
42686,WOODROW,02 TWO FAMILY DWELLINGS,1,7317,126,B2,112 ROBIN COURT,10309,2,0,2,11088,2160,1994,648000,2016-12-07,2016
42687,WOODROW,02 TWO FAMILY DWELLINGS,1,7349,34,B9,37 QUAIL LANE,10309,2,0,2,2400,2575,1998,450000,2016-11-28,2016
42688,WOODROW,02 TWO FAMILY DWELLINGS,1,7349,78,B9,32 PHEASANT LANE,10309,2,0,2,2498,2377,1998,550000,2017-04-21,2017
42689,WOODROW,02 TWO FAMILY DWELLINGS,1,7351,60,B2,49 PITNEY AVENUE,10309,2,0,2,4000,1496,1925,460000,2017-07-05,2017
42690,WOODROW,22 STORE BUILDINGS,4,7100,28,K6,2730 ARTHUR KILL ROAD,10309,0,7,7,208033,64117,2001,11693337,2016-12-21,2016
42691,WOODROW,35 INDOOR PUBLIC AND CULTURAL FACILITIES,4,7105,679,P9,155 CLAY PIT ROAD,10309,0,1,1,10796,2400,2006,69300,2016-10-27,2016

In [14]:
#Drop the "SALE DATE" column.
file.drop(['SALE DATE'], axis=1, inplace=True)
file

,NEIGHBORHOOD,BUILDING CLASS CATEGORY,TAX CLASS AT PRESENT,BLOCK,LOT,BUILDING CLASS AT PRESENT,ADDRESS,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,SALE PRICE,year of sale
0,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,2,387,153,D9,629 EAST 5TH STREET,10009,24,0,24,4489,18523,1920,16232000,2016
1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,2,376,14,C6,244 EAST 7TH STREET,10009,24,0,24,4131,16776,1928,11900000,2017
2,ALPHABET CITY,22 STORE BUILDINGS,4,390,34,K4,115 AVENUE C,10009,0,1,1,1218,3586,1899,3700000,2016
3,CHELSEA,01 ONE FAMILY DWELLINGS,1,771,52,A9,224 WEST 22ND STREET,10011,1,0,1,1975,3855,1901,7425000,2016
4,CHELSEA,01 ONE FAMILY DWELLINGS,1,772,29,A4,231 WEST 22ND STREET,10011,1,0,1,1588,5653,1900,10,2017
5,CHELSEA,01 ONE FAMILY DWELLINGS,1,772,29,A4,231 WEST 22ND STREET,10011,1,0,1,1588,5653,1900,10,2017
6,CHELSEA,01 ONE FAMILY DWELLINGS,1,772,29,A4,231 WEST 22ND STREET,10011,1,0,1,1588,5653,1900,10,2017
7,CHELSEA,02 TWO FAMILY DWELLINGS,1,769,49,S2,218 WEST 20TH STREET,10011,2,1,3,2150,4978,1920,7750000,2017
8,CHELSEA,03 THREE FAMILY DWELLINGS,1,719,67,C0,444 WEST 22ND STREET,10011,3,0,3,2469,3725,1901,8300000,2017
9,CHELSEA,07 RENTALS - WALKUP APARTMENTS,2,743,56,C5,318 WEST 20TH STREET,10011,24,0,24,2307,4500,1900,7375000,2017
10,CHELSEA,07 RENTALS - WALKUP APARTMENTS,2,764,68,C4,256 WEST 15TH STREET,10011,22,2,24,2581,13056,1901,14100000,2017
11,CHELSEA,07 RENTALS - WALKUP APARTMENTS,2,790,9,C7,147 WEST 14TH STREET,10011,15,1,16,2077,6335,1901,5500000,2017
12,CHELSEA,08 RENTALS - ELEVATOR APARTMENTS,2,794,11,D7,155 WEST 18TH,10011,30,2,32,10053,78882,2014,2341975,2016
13,CHELSEA,09 COOPS - WALKUP APARTMENTS,2,744,32,C6,309 WEST 20TH STREET,10011,24,0,24,4600,12200,1850,282000,2016
14,CHELSEA,21 OFFICE BUILDINGS,4,692,63,O2,558 WEST 21ST STREET,10011,0,3,3,1360,4080,1900,17300000,2017
15,CHELSEA,21 OFFICE BUILDINGS,4,790,32,O1,531-537 AVENUE OF THE AMER,10011,1,1,1,6468,14056,1953,42400000,2017
16,CHELSEA,21 OFFICE BUILDINGS,4,801,24,O3,119 WEST 25TH STREET,10001,0,13,13,9875,113062,1906,150000000,2016
17,CHELSEA,21 OFFICE BUILDINGS,4,801,58,O5,128 WEST 26TH STREET,10001,0,5,5,2469,10250,1930,10150000,2017
18,CHELSEA,22 STORE BUILDINGS,4,696,28,K1,507 WEST 24TH,10011,0,1,1,3950,7900,2013,10750000,2016
19,CHELSEA,22 STORE BUILDINGS,4,716,2,K4,132 TENTH AVENUE,10011,0,1,1,1675,3909,1910,8818181,2016
20,CHELSEA,22 STORE BUILDINGS,4,717,5,K1,459 WEST 19TH STREET,10011,0,1,1,3800,3800,1910,20000000,2017
21,CHELSEA,22 STORE BUILDINGS,4,773,1,K2,258 8 AVENUE,10011,0,4,4,19750,39500,1932,107250000,2017
22,CHELSEA,22 STORE BUILDINGS,4,790,36,K4,539 AVENUE OF THE AMER,10011,2,2,4,1586,4271,1920,10600000,2017
23,CHELSEA,23 LOFT BUILDINGS,4,795,19,L8,137 WEST 19TH STREET,10011,1,5,6,1878,11250,1910,10500000,2016
24,CHELSEA,23 LOFT BUILDINGS,4,799,63,L8,140 WEST 24TH STREET,10011,0,3,3,1852,3980,1920,9174156,2017
25,CHELSEA,23 LOFT BUILDINGS,4,801,19,L1,133 WEST 25TH STREET,10001,0,19,19,4937,45449,1921,33000000,2017
26,CHELSEA,25 LUXURY HOTELS,4,801,71,H1,152 WEST 26TH STREET,10001,0,1,1,9826,122236,2010,139725000,2016
27,CHELSEA,26 OTHER HOTELS,4,753,33,H8,305 WEST 29TH STREET,10001,0,1,1,2271,5260,1900,4300000,2017
28,CHELSEA,26 OTHER HOTELS,4,772,64,H3,216-222 WEST 23RD STREET,10011,0,10,10,17281,170750,1900,92007576,2016
29,CHELSEA,37 RELIGIOUS FACILITIES,4,799,25,M1,125 WEST 23RD STREET,10011,0,1,1,12343,21183,1920,50350000,2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42662,WOODROW,02 TWO FAMILY DWELLINGS,1,6967,25,B9,1019 RATHBUN AVENUE,10309,2,0,2,2500,1440,1987,595000,2017
42663,WOODROW,02 TWO FAMILY DWELLINGS,1,6967,37,B9,1035 RATHBUN AVENUE,10309,2,0,2,2500,1440,1987,445000,2016
42664,WOODROW,02 TWO FAMILY DWELLINGS,1,6970,26,B2,1053 SINCLAIR AVENUE,10309,2,0,2,8740,3160,1986,785000,2017
42665,WOODROW,02 TWO FAMILY DWELLINGS,1,7013,30,B2,60 MARISA CIRCLE,10309,2,0,2,2685,2265,1984,570000,2017
42666,WOODROW,02 TWO FAMILY DWELLINGS,1,7013,70,B2,136 MARISA CIRCLE,10309,2,0,2,3640,2576,1984,722000,2017
42667,WOODROW,02 TWO FAMILY DWELLINGS,1,7013,158,B2,149 MARISA CIRCLE,10309,2,0,2,2943,1976,1984,545000,2016
42668,WOODROW,02 TWO FAMILY DWELLINGS,1,7020,143,B2,1452 WOODROW ROAD,10309,2,0,2,11100,3560,1989,875000,2016
42669,WOODROW,02 TWO FAMILY DWELLINGS,1,7020,160,B2,574 MAGUIRE AVENUE,10309,2,0,2,21528,2650,1985,875000,2017
42670,WOODROW,02 TWO FAMILY DWELLINGS,1,7020,398,B2,72 DEXTER AVENUE,10309,2,0,2,5260,2600,2001,840000,2016
42671,WOODROW,02 TWO FAMILY DWELLINGS,1,7020,408,B2,56 DEXTER AVENUE,10309,2,0,2,8306,2600,2001,772500,2017
42672,WOODROW,02 TWO FAMILY DWELLINGS,1,7020,423,B2,35 LYNBROOK AVENUE,10309,2,0,2,5060,2600,2001,740000,2017
42673,WOODROW,02 TWO FAMILY DWELLINGS,1,7092,15,B9,96 CRABTREE AVENUE,10309,2,0,2,2337,1964,2010,590000,2017
42674,WOODROW,02 TWO FAMILY DWELLINGS,1,7092,113,B9,98 CRABTREE AVENUE,10309,2,0,2,2429,1798,2010,580000,2017
42675,WOODROW,02 TWO FAMILY DWELLINGS,1,7092,140,B9,10 TRINA LANE,10309,2,0,2,3936,1470,2004,550000,2017
42676,WOODROW,02 TWO FAMILY DWELLINGS,1,7105,2,B9,118 TURNER STREET,10309,2,0,2,6268,2206,2010,545000,2016
42677,WOODROW,02 TWO FAMILY DWELLINGS,1,7105,660,B2,125 CLAY PIT ROAD,10309,2,0,2,10935,2683,1998,800000,2017
42678,WOODROW,02 TWO FAMILY DWELLINGS,1,7267,130,B9,65 SHARROTTS LANE,10309,2,0,2,4300,2170,1998,642500,2017
42679,WOODROW,02 TWO FAMILY DWELLINGS,1,7267,131,B9,67 SHARROTTS LANE,10309,2,0,2,4700,2170,1998,408092,2016
42680,WOODROW,02 TWO FAMILY DWELLINGS,1,7267,182,B2,27 RED CEDAR LANE,10309,2,0,2,3985,2700,1996,600000,2017
42681,WOODROW,02 TWO FAMILY DWELLINGS,1,7267,202,B9,30 HEMLOCK LANE,10309,2,0,2,3801,2704,1996,610000,2016
42682,WOODROW,02 TWO FAMILY DWELLINGS,1,7267,218,B2,33 WHITE OAK LANE,10309,2,0,2,7885,2704,1996,645000,2017
42683,WOODROW,02 TWO FAMILY DWELLINGS,1,7267,244,B2,19 SPRUCE LANE,10309,2,0,2,3800,2700,1996,168000,2017
42684,WOODROW,02 TWO FAMILY DWELLINGS,1,7267,249,B2,48 WHITE OAK LANE,10309,2,0,2,4350,2840,1996,625000,2016
42685,WOODROW,02 TWO FAMILY DWELLINGS,1,7316,93,B2,125 DARNELL LANE,10309,2,0,2,3325,1300,1995,509000,2016
42686,WOODROW,02 TWO FAMILY DWELLINGS,1,7317,126,B2,112 ROBIN COURT,10309,2,0,2,11088,2160,1994,648000,2016
42687,WOODROW,02 TWO FAMILY DWELLINGS,1,7349,34,B9,37 QUAIL LANE,10309,2,0,2,2400,2575,1998,450000,2016
42688,WOODROW,02 TWO FAMILY DWELLINGS,1,7349,78,B9,32 PHEASANT LANE,10309,2,0,2,2498,2377,1998,550000,2017
42689,WOODROW,02 TWO FAMILY DWELLINGS,1,7351,60,B2,49 PITNEY AVENUE,10309,2,0,2,4000,1496,1925,460000,2017
42690,WOODROW,22 STORE BUILDINGS,4,7100,28,K6,2730 ARTHUR KILL ROAD,10309,0,7,7,208033,64117,2001,11693337,2016
42691,WOODROW,35 INDOOR PUBLIC AND CULTURAL FACILITIES,4,7105,679,P9,155 CLAY PIT ROAD,10309,0,1,1,10796,2400,2006,69300,2016

In [15]:
#Get dummy encoded columns for 'TAX CLASS AT PRESENT' predictor.
pd.get_dummies(file, columns=['TAX CLASS AT PRESENT'])

,NEIGHBORHOOD,BUILDING CLASS CATEGORY,BLOCK,LOT,BUILDING CLASS AT PRESENT,ADDRESS,ZIP CODE,RESIDENTIAL UNITS,COMMERCIAL UNITS,TOTAL UNITS,LAND SQUARE FEET,GROSS SQUARE FEET,YEAR BUILT,SALE PRICE,year of sale,TAX CLASS AT PRESENT_1,TAX CLASS AT PRESENT_2,TAX CLASS AT PRESENT_3,TAX CLASS AT PRESENT_4
0,ALPHABET CITY,08 RENTALS - ELEVATOR APARTMENTS,387,153,D9,629 EAST 5TH STREET,10009,24,0,24,4489,18523,1920,16232000,2016,0,1,0,0
1,ALPHABET CITY,09 COOPS - WALKUP APARTMENTS,376,14,C6,244 EAST 7TH STREET,10009,24,0,24,4131,16776,1928,11900000,2017,0,1,0,0
2,ALPHABET CITY,22 STORE BUILDINGS,390,34,K4,115 AVENUE C,10009,0,1,1,1218,3586,1899,3700000,2016,0,0,0,1
3,CHELSEA,01 ONE FAMILY DWELLINGS,771,52,A9,224 WEST 22ND STREET,10011,1,0,1,1975,3855,1901,7425000,2016,1,0,0,0
4,CHELSEA,01 ONE FAMILY DWELLINGS,772,29,A4,231 WEST 22ND STREET,10011,1,0,1,1588,5653,1900,10,2017,1,0,0,0
5,CHELSEA,01 ONE FAMILY DWELLINGS,772,29,A4,231 WEST 22ND STREET,10011,1,0,1,1588,5653,1900,10,2017,1,0,0,0
6,CHELSEA,01 ONE FAMILY DWELLINGS,772,29,A4,231 WEST 22ND STREET,10011,1,0,1,1588,5653,1900,10,2017,1,0,0,0
7,CHELSEA,02 TWO FAMILY DWELLINGS,769,49,S2,218 WEST 20TH STREET,10011,2,1,3,2150,4978,1920,7750000,2017,1,0,0,0
8,CHELSEA,03 THREE FAMILY DWELLINGS,719,67,C0,444 WEST 22ND STREET,10011,3,0,3,2469,3725,1901,8300000,2017,1,0,0,0
9,CHELSEA,07 RENTALS - WALKUP APARTMENTS,743,56,C5,318 WEST 20TH STREET,10011,24,0,24,2307,4500,1900,7375000,2017,0,1,0,0
10,CHELSEA,07 RENTALS - WALKUP APARTMENTS,764,68,C4,256 WEST 15TH STREET,10011,22,2,24,2581,13056,1901,14100000,2017,0,1,0,0
11,CHELSEA,07 RENTALS - WALKUP APARTMENTS,790,9,C7,147 WEST 14TH STREET,10011,15,1,16,2077,6335,1901,5500000,2017,0,1,0,0
12,CHELSEA,08 RENTALS - ELEVATOR APARTMENTS,794,11,D7,155 WEST 18TH,10011,30,2,32,10053,78882,2014,2341975,2016,0,1,0,0
13,CHELSEA,09 COOPS - WALKUP APARTMENTS,744,32,C6,309 WEST 20TH STREET,10011,24,0,24,4600,12200,1850,282000,2016,0,1,0,0
14,CHELSEA,21 OFFICE BUILDINGS,692,63,O2,558 WEST 21ST STREET,10011,0,3,3,1360,4080,1900,17300000,2017,0,0,0,1
15,CHELSEA,21 OFFICE BUILDINGS,790,32,O1,531-537 AVENUE OF THE AMER,10011,1,1,1,6468,14056,1953,42400000,2017,0,0,0,1
16,CHELSEA,21 OFFICE BUILDINGS,801,24,O3,119 WEST 25TH STREET,10001,0,13,13,9875,113062,1906,150000000,2016,0,0,0,1
17,CHELSEA,21 OFFICE BUILDINGS,801,58,O5,128 WEST 26TH STREET,10001,0,5,5,2469,10250,1930,10150000,2017,0,0,0,1
18,CHELSEA,22 STORE BUILDINGS,696,28,K1,507 WEST 24TH,10011,0,1,1,3950,7900,2013,10750000,2016,0,0,0,1
19,CHELSEA,22 STORE BUILDINGS,716,2,K4,132 TENTH AVENUE,10011,0,1,1,1675,3909,1910,8818181,2016,0,0,0,1
20,CHELSEA,22 STORE BUILDINGS,717,5,K1,459 WEST 19TH STREET,10011,0,1,1,3800,3800,1910,20000000,2017,0,0,0,1
21,CHELSEA,22 STORE BUILDINGS,773,1,K2,258 8 AVENUE,10011,0,4,4,19750,39500,1932,107250000,2017,0,0,0,1
22,CHELSEA,22 STORE BUILDINGS,790,36,K4,539 AVENUE OF THE AMER,10011,2,2,4,1586,4271,1920,10600000,2017,0,0,0,1
23,CHELSEA,23 LOFT BUILDINGS,795,19,L8,137 WEST 19TH STREET,10011,1,5,6,1878,11250,1910,10500000,2016,0,0,0,1
24,CHELSEA,23 LOFT BUILDINGS,799,63,L8,140 WEST 24TH STREET,10011,0,3,3,1852,3980,1920,9174156,2017,0,0,0,1
25,CHELSEA,23 LOFT BUILDINGS,801,19,L1,133 WEST 25TH STREET,10001,0,19,19,4937,45449,1921,33000000,2017,0,0,0,1
26,CHELSEA,25 LUXURY HOTELS,801,71,H1,152 WEST 26TH STREET,10001,0,1,1,9826,122236,2010,139725000,2016,0,0,0,1
27,CHELSEA,26 OTHER HOTELS,753,33,H8,305 WEST 29TH STREET,10001,0,1,1,2271,5260,1900,4300000,2017,0,0,0,1
28,CHELSEA,26 OTHER HOTELS,772,64,H3,216-222 WEST 23RD STREET,10011,0,10,10,17281,170750,1900,92007576,2016,0,0,0,1
29,CHELSEA,37 RELIGIOUS FACILITIES,799,25,M1,125 WEST 23RD STREET,10011,0,1,1,12343,21183,1920,50350000,2016,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42662,WOODROW,02 TWO FAMILY DWELLINGS,6967,25,B9,1019 RATHBUN AVENUE,10309,2,0,2,2500,1440,1987,595000,2017,1,0,0,0
42663,WOODROW,02 TWO FAMILY DWELLINGS,6967,37,B9,1035 RATHBUN AVENUE,10309,2,0,2,2500,1440,1987,445000,2016,1,0,0,0
42664,WOODROW,02 TWO FAMILY DWELLINGS,6970,26,B2,1053 SINCLAIR AVENUE,10309,2,0,2,8740,3160,1986,785000,2017,1,0,0,0
42665,WOODROW,02 TWO FAMILY DWELLINGS,7013,30,B2,60 MARISA CIRCLE,10309,2,0,2,2685,2265,1984,570000,2017,1,0,0,0
42666,WOODROW,02 TWO FAMILY DWELLINGS,7013,70,B2,136 MARISA CIRCLE,10309,2,0,2,3640,2576,1984,722000,2017,1,0,0,0
42667,WOODROW,02 TWO FAMILY DWELLINGS,7013,158,B2,149 MARISA CIRCLE,10309,2,0,2,2943,1976,1984,545000,2016,1,0,0,0
42668,WOODROW,02 TWO FAMILY DWELLINGS,7020,143,B2,1452 WOODROW ROAD,10309,2,0,2,11100,3560,1989,875000,2016,1,0,0,0
42669,WOODROW,02 TWO FAMILY DWELLINGS,7020,160,B2,574 MAGUIRE AVENUE,10309,2,0,2,21528,2650,1985,875000,2017,1,0,0,0
42670,WOODROW,02 TWO FAMILY DWELLINGS,7020,398,B2,72 DEXTER AVENUE,10309,2,0,2,5260,2600,2001,840000,2016,1,0,0,0
42671,WOODROW,02 TWO FAMILY DWELLINGS,7020,408,B2,56 DEXTER AVENUE,10309,2,0,2,8306,2600,2001,772500,2017,1,0,0,0
42672,WOODROW,02 TWO FAMILY DWELLINGS,7020,423,B2,35 LYNBROOK AVENUE,10309,2,0,2,5060,2600,2001,740000,2017,1,0,0,0
42673,WOODROW,02 TWO FAMILY DWELLINGS,7092,15,B9,96 CRABTREE AVENUE,10309,2,0,2,2337,1964,2010,590000,2017,1,0,0,0
42674,WOODROW,02 TWO FAMILY DWELLINGS,7092,113,B9,98 CRABTREE AVENUE,10309,2,0,2,2429,1798,2010,580000,2017,1,0,0,0
42675,WOODROW,02 TWO FAMILY DWELLINGS,7092,140,B9,10 TRINA LANE,10309,2,0,2,3936,1470,2004,550000,2017,1,0,0,0
42676,WOODROW,02 TWO FAMILY DWELLINGS,7105,2,B9,118 TURNER STREET,10309,2,0,2,6268,2206,2010,545000,2016,1,0,0,0
42677,WOODROW,02 TWO FAMILY DWELLINGS,7105,660,B2,125 CLAY PIT ROAD,10309,2,0,2,10935,2683,1998,800000,2017,1,0,0,0
42678,WOODROW,02 TWO FAMILY DWELLINGS,7267,130,B9,65 SHARROTTS LANE,10309,2,0,2,4300,2170,1998,642500,2017,1,0,0,0
42679,WOODROW,02 TWO FAMILY DWELLINGS,7267,131,B9,67 SHARROTTS LANE,10309,2,0,2,4700,2170,1998,408092,2016,1,0,0,0
42680,WOODROW,02 TWO FAMILY DWELLINGS,7267,182,B2,27 RED CEDAR LANE,10309,2,0,2,3985,2700,1996,600000,2017,1,0,0,0
42681,WOODROW,02 TWO FAMILY DWELLINGS,7267,202,B9,30 HEMLOCK LANE,10309,2,0,2,3801,2704,1996,610000,2016,1,0,0,0
42682,WOODROW,02 TWO FAMILY DWELLINGS,7267,218,B2,33 WHITE OAK LANE,10309,2,0,2,7885,2704,1996,645000,2017,1,0,0,0
42683,WOODROW,02 TWO FAMILY DWELLINGS,7267,244,B2,19 SPRUCE LANE,10309,2,0,2,3800,2700,1996,168000,2017,1,0,0,0
42684,WOODROW,02 TWO FAMILY DWELLINGS,7267,249,B2,48 WHITE OAK LANE,10309,2,0,2,4350,2840,1996,625000,2016,1,0,0,0
42685,WOODROW,02 TWO FAMILY DWELLINGS,7316,93,B2,125 DARNELL LANE,10309,2,0,2,3325,1300,1995,509000,2016,1,0,0,0
42686,WOODROW,02 TWO FAMILY DWELLINGS,7317,126,B2,112 ROBIN COURT,10309,2,0,2,11088,2160,1994,648000,2016,1,0,0,0
42687,WOODROW,02 TWO FAMILY DWELLINGS,7349,34,B9,37 QUAIL LANE,10309,2,0,2,2400,2575,1998,450000,2016,1,0,0,0
42688,WOODROW,02 TWO FAMILY DWELLINGS,7349,78,B9,32 PHEASANT LANE,10309,2,0,2,2498,2377,1998,550000,2017,1,0,0,0
42689,WOODROW,02 TWO FAMILY DWELLINGS,7351,60,B2,49 PITNEY AVENUE,10309,2,0,2,4000,1496,1925,460000,2017,1,0,0,0
42690,WOODROW,22 STORE BUILDINGS,7100,28,K6,2730 ARTHUR KILL ROAD,10309,0,7,7,208033,64117,2001,11693337,2016,0,0,0,1
42691,WOODROW,35 INDOOR PUBLIC AND CULTURAL FACILITIES,7105,679,P9,155 CLAY PIT ROAD,10309,0,1,1,10796,2400,2006,69300,2016,0,0,0,1